POST http://localhost:3333/products
Content-type: application/json

{
    "brand_id": "0001",
    "name": "roupa 01", 
    "description": "Roupa bonita", 
    "unit_price": 100, 
    "total_stock_quantity": 50, 
    "created_at": "01/01/2004", 
    "updated_at": "01/01/2004", 
    "is_active": "true"
}